kind: pipeline
name: Jekyll build
type: docker


steps:

- name: build
  image: ruby
  commands:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  
---  
kind: pipeline
type: docker
name: MegaLinter

workspace:
  path: /tmp/lint

steps: 

- name: megalinter
  image: oxsecurity/megalinter:v6
  environment:
    DEFAULT_WORKSPACE: /tmp/lint