kind: pipeline
name: Jekyll build
type: docker

steps:
- name: build
  image: ruby
  commands:
  - gem update  
  - gem install bundler
  - bundle install
  - bundle update
  - bundle exec jekyll build