#theme: jekyll-theme-potato-hacker
repository: d-eathrow/anonymousland
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"
#theme_switch: on 
blog: on
avatar: off
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:
  - Guides
  - dropdown1
  - dropdown2
  - blog
collections:
  guide:
    output: true
  dropdown:
    output: true
  items:
    output: true