repository: anonymousland/anonymousland
theme: jekyll-theme-potato-hacker
theme_base: "dark"
theme_switch: off
blog: on
highlighter_theme: monokai
toolbar_priority: 
  - blog
collections:
  .well-known:
    output: true
    permalink: /:collection/:path/
  items:
    output: true
  changelog:
    output: true
  pages:
    output: true
  information:
    output: true
exclude:
#  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-feed
  - jekyll-seo-tag
feed:
  collections:
    - changelog
    - information
    - items
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

webrick:
  headers:
    Content-Security-Policy: default-src 'self';
    Strict-Transport-Security: max-age=31536000; includeSubDomains