# frozen_string_literal: true
source "https://rubygems.org"
gem "jekyll"
gem "jekyll-theme-potato-hacker"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "kramdown-parser-gfm"
gem "bundler"
gem "webrick"