name: Jekyll build
on: [push]

jobs:
  lint:
    name: build
    runs-on: ruby:3.1.3
    steps:
      commands:
         - gem update  
         - gem install bundler
         - bundle install
         - bundle exec jekyll build